name: HOOT CI Pipeline

on:
  push:
    branches: [development, production]

jobs:
  build-and-test:
    name: Build, Lint, & Test
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"

      - name: Install Dependencies
        run: npm ci

      - name: Lint Code
        run: npm run lint    

      - name: Run Unit Tests
        env:
          NODE_ENV: test
          SESSION_SECRET: test_secret
        run: npm test

      - name: Run Integration Tests
        env:
          NODE_ENV: integration_test
          MONGODB_URI_CI: ${{ secrets.MONGODB_URI_CI }}
          TEACHER_CODE: ${{ secrets.TEACHER_CODE }}
          SESSION_SECRET: ${{ secrets.SESSION_SECRET }} 
        run: npm run test:int

